const allSectionsAndSubSections = [
	{
		heading: "News",
		navBar: true,
		color: "red",
		items: [
			"Irish News",
			"Dublin",
			"World News",
			"Local News",
			"Local ePapers",
			"Environment",
			"Weather",
			"Latest News",
			"Video",
			"Topics",
		],
	},
	{
		heading: "Opinion",
		navBar: true,
		color: "gray",
		items: ["Letters", "Editorial", "Comment", "Journalists"],
	},
	{
		heading: "Business",
		navBar: true,
		color: "blue",
		items: [
			"Budget 2023",
			"Irish",
			"World",
			"Technology",
			"Personal Finance",
			"Small Business",
			"Farming",
			"Jobs",
			"Commercial Property",
			"In The Workplace",
		],
	},
	{
		heading: "Sport",
		navBar: true,
		color: "darkOrange",
		items: [
			"Rugby",
			"GAA",
			"Soccer",
			"SportStar Awards",
			"The Left Wing",
			"The Throw In",
			"Women's Sport",
			"Golf",
			"Horse Racing",
			"Other Sports",
			"ICycle",
		],
	},
	{
		heading: "Life",
		navBar: true,
		color: "green",
		items: [
			"Christmas",
			"Health & Wellbeing",
			"Home & Garden",
			"Family",
			"Parenting",
			"Food & Drink",
			"Motoring",
		],
	},
	{
		heading: "Style",
		navBar: true,
		color: "darkRed",
		items: [
			"Celebrity",
			"Fashion",
			"Beauty",
			"Sex & Relationships",
			"Voices",
			"Galleries",
		],
	},
	{
		heading: "Entertainment",
		navBar: true,
		color: "orange",
		items: [
			"Movies",
			"Television",
			"Music",
			"Radio",
			"Books",
			"Theatre & Arts",
			"Games",
			"Festivals",
			"Puzzles",
			"Horoscopes",
			"Competitions",
		],
	},
	{
		heading: "Travel",
		color: "darkBlue",
		navBar: true,
		items: [
			"Reader Travel Awards",
			"Travel News",
			"StayCations",
			"Ireland",
			"Reviews",
			"Walks",
			"Europe",
			"World/USA",
			"Travel TV",
			"Cruise",
			"Ski",
		],
	},
	{
		heading: "Podcasts",
		color: "darkGray",
		items: [
			"The InDo Daily",
			"InDo Daily - Original Series",
			"The Left Wing",
			"The Big Tech Show",
			"Real Health Podcast",
			"The Throw In",
			"InDo World Cup",
		],
	},
	{
		heading: "About Us",
		color: "darkslateblue",
		items: [
			"Video",
			"Newsletter",
			"CarsIreland.ie",
			"CarZone.ie",
			"CarTell.ie",
			"Switcher.ie",
			"Discount Codes",
			"Reach DelPack",
			"Socials",
		],
	},
];

export default allSectionsAndSubSections;
